### ISSUE TITLE
No dask scheduler

### ISSUE THREAD

**Issue by tedhabermann** [geospace-code/georinex#67]
1. There are many types of RINEX files.
     Almost every issue is because of some corner case with a particular RINEX format.
     Thus we will usually need a copy of your RINEX file.
     If it's very large/private, consider copying just the part of it that causes the issue for you.
2. Please copy and paste the error traceback, to help find which function the error is occurring in.
3. generally a dump of all the versions of Python packages you have is **not** needed

I am trying to read a rinex file from UNAVCO on a mac: ftp://data-out.unavco.org/pub/rinex3/obs/2020/257/ARVL00ATA_R_20202570000_01D_15S_MO.crx.gz
and get this error:
georinex_read ARVL00ATA_R_20202570000_01D_15S_MO.rnx -v -o ARVL00ATA_R_20202570000_01D_15S_MO.nc
saving OBS: ARVL00ATA_R_20202570000_01D_15S_MO.nc
Traceback (most recent call last):
  File "/Users/tedhabermann/anaconda3/bin/georinex_read", line 8, in <module>
    sys.exit(georinex_read())
  File "/Users/tedhabermann/anaconda3/lib/python3.6/site-packages/georinex/__main__.py", line 51, in georinex_read
    verbose=P.verbose, fast=P.strict, interval=P.interval)
  File "/Users/tedhabermann/anaconda3/lib/python3.6/site-packages/georinex/base.py", line 69, in load
    overwrite=overwrite, fast=fast, interval=interval)
  File "/Users/tedhabermann/anaconda3/lib/python3.6/site-packages/georinex/base.py", line 207, in rinexobs
    obs.to_netcdf(outfn, group=group, mode=wmode, encoding=enc)
  File "/Users/tedhabermann/anaconda3/lib/python3.6/site-packages/xarray/core/dataset.py", line 1568, in to_netcdf
    invalid_netcdf=invalid_netcdf,
  File "/Users/tedhabermann/anaconda3/lib/python3.6/site-packages/xarray/backends/api.py", line 1044, in to_netcdf
    scheduler = _get_scheduler()
  File "/Users/tedhabermann/anaconda3/lib/python3.6/site-packages/xarray/backends/locks.py", line 79, in _get_scheduler
    actual_get = dask.base.get_scheduler(get, collection)
AttributeError: module 'dask.base' has no attribute 'get_scheduler'

**Comment by tedhabermann** [comment]
This was caused by old version of dask. Updated dask and scipy and all is well.
